version: 2
builds:
  - id: default
    main: ./cmd/koyeb
    binary: koyeb
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: "386"
    ldflags:
      - -X github.com/koyeb/koyeb-cli/pkg/koyeb.BuildDate={{ .Date }}
      - -X github.com/koyeb/koyeb-cli/pkg/koyeb.Version={{ .Version }}
      - -X github.com/koyeb/koyeb-cli/pkg/koyeb.Commit={{ .ShortCommit }}
  - id: windows
    main: ./cmd/koyeb
    binary: koyeb
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    ignore:
      - goos: windows
        goarch: "386"
    ldflags:
      - -X github.com/koyeb/koyeb-cli/pkg/koyeb.BuildDate={{ .Date }}
      - -X github.com/koyeb/koyeb-cli/pkg/koyeb.Version={{ .Version }}
      - -X github.com/koyeb/koyeb-cli/pkg/koyeb.Commit={{ .ShortCommit }}

archives:
  - id: windows
    builds:
      - windows
    wrap_in_directory: false
    format: zip
  - id: default
    builds:
      - default
    files: [only-the-binary*]
    wrap_in_directory: false
    format: tar.gz

release:
  prerelease: auto

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "koyeb/koyeb-cli:latest"
      - "koyeb/koyeb-cli:v{{ .Version }}"
    skip_push: auto

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{.Branch}}-{{.ShortCommit}}"

brews:
  - repository:
      owner: koyeb
      name: homebrew-tap
    name: koyeb
    directory: Formula
    homepage: https://koyeb.com
    skip_upload: auto
    test: |
      system "#{bin}/koyeb version"
    install: |
      bin.install "koyeb"
